In [ ]:
import datetime
print(f"Notebook last run(end to end):{datetime.datetime.now()}")

Notebook last run(end to end):2026-03-14 17:13:44.467846


In [ ]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [ ]:
scalar=tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

creating tensor more than 0 dimension

In [ ]:
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix=tf.constant([[1,0],[0,1]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 1]], dtype=int32)>

In [ ]:
matrix.ndim

2

Create another matrix and define the datatype



In [ ]:
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16)
tf.random.shuffle(another_matrix)

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 8.,  9.],
       [ 3.,  2.],
       [10.,  7.]], dtype=float16)>

creating tensor with varaiabe

In [ ]:

changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

Random Tensor Generation


In [ ]:
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2=tf.random.Generator.from_seed(11)
random_2=random_2.normal(shape=(3,2))
random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.2730574 , -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130817 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

Rank,size,dimension,shape


In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#create a 4 rank tensor
rank_4_tensor= tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
print("Tensor rank",rank_4_tensor.ndim)
print("Tensor shape",rank_4_tensor.shape)
print("Tensor size",tf.size(rank_4_tensor).numpy())
print("tensor data type ",rank_4_tensor.dtype)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])

Tensor rank 4
Tensor shape (2, 3, 4, 5)
Tensor size 120
tensor data type  <dtype: 'float32'>
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5


In [ ]:
#tensor indexes
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add an extra dimension (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [ ]:
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

Manipulating Tensors


In [ ]:
#basic operations
tensor=tf.constant([[1,2],[4,8]])
tensor+10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [14, 18]], dtype=int32)>

In [ ]:
#as done on constant tensor ,original copy will remain unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 8]], dtype=int32)>

In [ ]:
# Multiplication (known as element-wise multiplication)
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [40, 80]], dtype=int32)>

In [ ]:
#equivalent method of multiplication
tf.multiply(tensor, 10)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [40, 80]], dtype=int32)>

In [ ]:
# Matrix multiplication in TensorFlow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[1 2]
 [4 8]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9, 18],
       [36, 72]], dtype=int32)>

In [ ]:
#multiplying two tensors of same dimensions(just to chck)
tensor_1=tf.zeros(shape=(3,2))
tensor_2=tf.ones(shape=(3,2))
tensor_1@tensor_2

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:GPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [ ]:
# Example of reshape (3, 2) -> (2, 3)
tf.reshape(tensor_2, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
tensor_1@tf.reshape(tensor_2, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
tensor_1@tf.reshape(tensor_2, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
tensor = tf.constant([[1, 2, 3],
                      [4, 5, 6]])  # shape (2,3)

In [ ]:
# Check values of tensor, reshape tensor and tranposed tensor
print("Normal Tensor:")
print(tensor, "\n") # "\n" for newline

print("Tensor reshaped to (2, 3):")
print(tf.reshape(tensor,(3, 2)), "\n")

print("Tensor transposed:")
print(tf.transpose(tensor))

Normal Tensor:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32) 

Tensor reshaped to (2, 3):
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32) 

Tensor transposed:
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


changing data type of tensor


In [ ]:
c=tf.constant([[-1,2],[4,6]])
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-1,  2],
       [ 4,  6]], dtype=int32)>

In [ ]:
# Change from int32 to float32
C = tf.cast(c, dtype=tf.float32)
C

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.,  2.],
       [ 4.,  6.]], dtype=float32)>

In [ ]:
#getting absolute value
tf.abs(c)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 6]], dtype=int32)>

In [ ]:
#finding min,max,mean,sum
b=tf.constant([2,3,4])
print(tf.reduce_min(b))
print(tf.reduce_max(b))
print(tf.reduce_mean(b))
print(tf.reduce_sum(b))

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


finding positional max and min


In [ ]:
# Create a tensor with 50 values between 0 and 1
import numpy as np
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.16883587, 0.67323845, 0.01334283, 0.17287505, 0.5041302 ,
       0.42496961, 0.91746861, 0.37534539, 0.98376716, 0.77558882,
       0.06284588, 0.60285952, 0.53586493, 0.91528082, 0.65782149,
       0.54681254, 0.24511278, 0.57406964, 0.87459718, 0.31511362,
       0.23716717, 0.49875005, 0.48910139, 0.82458427, 0.81636607,
       0.00314267, 0.31649346, 0.63596485, 0.52538702, 0.74633943,
       0.37522066, 0.46464905, 0.88605868, 0.89669136, 0.96905572,
       0.33395873, 0.69107687, 0.22015386, 0.47973535, 0.98549908,
       0.49009714, 0.84896351, 0.25639258, 0.25313774, 0.35132474,
       0.44940138, 0.9005957 , 0.62515905, 0.89163943, 0.75446385])>

In [ ]:
# Find the maximum element position of F
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=39>

In [ ]:
# Find the minimum element position of F
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=25>

In [ ]:
# Find the maximum element position of F
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}")
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}")
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

The maximum value of F is at position: 39
The maximum value of F is: 0.9854990810244938
Using tf.argmax() to index F, the maximum value of F is: 0.9854990810244938
Are the two max values the same (they should be)? True


Squeezing a Tensor (Removing all Single elements)


In [ ]:
# Create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [ ]:
# Squeeze tensor G (remove all 1 dimensions)
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

One Hot Encoding

In [ ]:
# Create a list of indices
some_list = [0, 1, 2, 3]

# One hot encode them
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for on and off encoding
tf.one_hot(some_list, depth=4, on_value="We're live!", off_value="Offline")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"We're live!", b'Offline', b'Offline', b'Offline'],
       [b'Offline', b"We're live!", b'Offline', b'Offline'],
       [b'Offline', b'Offline', b"We're live!", b'Offline'],
       [b'Offline', b'Offline', b'Offline', b"We're live!"]], dtype=object)>

square,square root,log

In [ ]:
a=tf.constant([1,2,3])
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
#square
tf.square(a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9], dtype=int32)>

In [ ]:
#square root
tf.sqrt(a)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt] name: 

In [ ]:
a=tf.cast(a,dtype=tf.float32)
tf.sqrt(a)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.       , 1.4142135, 1.7320508], dtype=float32)>

In [ ]:
#log
tf.math.log(a)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.       , 0.6931472, 1.0986123], dtype=float32)>

creating tensor from numpy and from an array

In [ ]:
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64
tensor_J = tf.constant([3., 7., 10.]) # will be float32
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

Using tf.function

In [ ]:
# Create a simple function
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [ ]:
# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)
#difference happens behind the scene

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

Checking if GPU is available or not

In [ ]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [ ]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
